python -u train.py \
    --model vRNN \
    --epochs 5 \
    --lr 0.1 \
    --weight-decay 0.0 \
    --batch-size 128 \
    --hidden_dim 50 \
    --dropout 0.0 \
    --num_layers 1 \
    --useGlove False \
    --trainable False \
    --bidirectional False \
    --typeOfPadding padded | tee vRNN.log
