python -u train.py \
    --model vRNN \
    --epochs 5 \
    --lr 0.01 \
    --weight-decay 0.0 \
    --batch-size 1000 \
    --hidden_dim 150 \
    --dropout 0.0 \
    --num_layers 1 \
    --useGlove True \
    --trainable True \
    --bidirectional True \
    --typeOfPadding no_padding | tee vRNN.log
